# Uncomment the next line to define a global platform for your project
source "https://github.com/CocoaPods/Specs.git"
platform :ios, '11.0'

workspace 'BUADDemo.xcworkspace'

abstract_target 'Demo' do
    pod 'AFNetworking', '~> 3.0', :subspecs => ['UIKit'], :inhibit_warnings => false
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'SDWebImage'

    target 'BUADDemo' do
      project 'BUADDemo.xcodeproj'
      # 本target相较于BUADDemo Target多了聚合维度功能展示
    #    pod 'MentaVlionSDK', "5.20.32.1"
    #    pod 'BUMentaCustomAdapter', '5.20.32'
      
       pod 'BUDemoSource',         :path => '../'
       pod 'BUMentaCustomAdapter', :path => '../'
     
#      pod 'MentaVlionBaseSDK',    :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionBaseSDK.podspec'
#      pod 'MentaVlionSDK',        :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionSDK.podspec'
#      pod 'MentaUnifiedSDK',      :path => '/Users/jdy/Desktop/Menta-iOS/MentaUnifiedSDK.podspec'
#      pod 'MentaVlionAdapter',    :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionAdapter.podspec'
       
    #    pod 'MentaVlionBaseSDK',    '5.20.34'
    #    pod 'MentaUnifiedSDK',      '5.20.34'
    #    pod 'MentaVlionSDK',        '5.20.34'
    #    pod 'MentaVlionAdapter',    '5.20.34'
    #    pod 'MentaJDYunAdapter',    '5.20.34'
    #    pod 'MentaTanxAdapter',     '5.20.34'
        
      end
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
